# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TubulrExtension' do

	pod 'hpple', '~> 0.2'
	pod 'AFNetworking', '~> 2.4.1'
	pod 'MCSwipeTableViewCell', '~> 2.1'
	pod 'FontAwesomeKit/FontAwesome'

end

target 'TubulrExtensionTests' do

	pod 'Expecta',     '~> 0.2.4'
	pod 'Specta'

end

target 'TubulrShare' do

	pod 'hpple', '~> 0.2'
	pod 'AFNetworking', '~> 2.4.1'
	pod 'MCSwipeTableViewCell', '~> 2.1'
	pod 'FontAwesomeKit/FontAwesome'

end

